set_master_offset:
  fields:
    offset:
      required: true
      selector:
        number:
          min: -5
          max: 5
          step: 0.5
          unit_of_measurement: "°C"
          mode: slider
